# Generated by Django 3.2.5 on 2022-11-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mem_email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField()),
                ('field', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutBank',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='address',
            new_name='off_address',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='email',
            new_name='off_email',
        ),
    ]
