# Generated by Django 3.2.5 on 2022-11-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221102_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('callback_date', models.IntegerField()),
                ('callback_time', models.IntegerField()),
                ('message', models.TextField(default=None)),
            ],
        ),
    ]
