# Generated by Django 4.1.3 on 2022-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_aboutform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutform',
            name='callback_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutform',
            name='callback_time',
            field=models.IntegerField(null=True),
        ),
    ]
